### ISSUE TITLE
Tags missing

### ISSUE THREAD

**Issue by samwebster** [samwebster/times-excel-reader#2]
@Antti-L noticed that the tag list is missing the following tables: TFM_MIG and TFM_DINS_TS.
Is it the list in [times_mapping](https://github.com/microsoft/times-excel-reader/blob/main/times_mapping.txt)?

From https://github.com/microsoft/times-excel-reader/issues/17

**Comment by olejandro** [comment]
Proposed #49 to include all the missing tags in datatypes

**Comment by olejandro** [comment]
Introduced a complete list of tags with 2acbaa92a783727457c4682958d446a50cbc0587
