### ISSUE TITLE
Columns with the same name get overwritten

### ISSUE THREAD

**Issue by olejandro** [samwebster/times-excel-reader#24]
> @samwebster @siddharth-krishna there seems to be a bug in processing the following line `TOP_IRE[ALL_REG,COM,ALL_REG,COM,PRC] = TOP_IRE(Source,IN,Destination,OUT,TechName)`. It looks like one column gets overwritten by another column, because they have same name.

_Originally posted by @olejandro in https://github.com/samwebster/times-excel-reader/issues/23#issuecomment-1442859619_

**Comment by samwebster** [comment]
We should probably drop this mapping and emit a warning about duplicate names
