### ISSUE TITLE
Collapse Comm-IN and Comm-Out down to single column in processed FI_T

### ISSUE THREAD

**Issue by samwebster** [samwebster/times-excel-reader#27]
See https://github.com/samwebster/times-excel-reader/pull/26#pullrequestreview-1314062347

**Comment by olejandro** [comment]
Only CommName is used to generate outputs since 3f283707120f82b74f7be5c8ff93736acb8f66f7
Let's keep Comm-IN and Comm-OUT for now, just in case we need them for some processing steps.
