### ISSUE TITLE
Nondeterministic behaviour on Ireland model

### ISSUE THREAD

**Issue by siddharth-krishna** [samwebster/times-excel-reader#50]
There's some source of nondeterminism when running our tool on (Sam's fork of) the Ireland model... sometimes we get 23836 and 14002 correct and additional rows, and sometimes 23835 and 14014. 

See the two runs on the same commit here: (Click "Latest #2" on the top-right to see previous)
https://github.com/samwebster/times-excel-reader/actions/runs/4367762835

I think we should aim for determinism and reproducibility.

**Comment by olejandro** [comment]
Let's keep checking on this...

**Comment by olejandro** [comment]
Actually, I also see this difference when I run the tool locally.

**Comment by olejandro** [comment]
Or maybe not... Seems that when I run `main` and `PR` locally, in both cases 10 records more are in ground trought and 10 records less are in additional rows compared to what's produced by the Action.

**Comment by siddharth-krishna** [comment]
Another example: https://github.com/samwebster/times-excel-reader/actions/runs/4428275638/jobs/7767113656
This PR doesn't change the tool at all (it only changes the print statement in `run_benchmarks.py`), so it shouldn't cause a regression.

**Comment by olejandro** [comment]
Have a feeling that both #65 and #66 are also affected by this...

**Comment by siddharth-krishna** [comment]
I found the source of non determinism! I'll open a PR tomorrow
