### ISSUE TITLE
Review TIMES mapping approach

### ISSUE THREAD

**Issue by olejandro** [samwebster/times-excel-reader#52]
Is the duplicate mapping intentional? Does the second mapping just overwrite the first one?

_Originally posted by @siddharth-krishna in https://github.com/samwebster/times-excel-reader/pull/42#discussion_r1132095539_

**Comment by olejandro** [comment]
@siddharth-krishna do you think we can close this issue?

**Comment by siddharth-krishna** [comment]
Closing this issue and continuing the discussion in #57
