### ISSUE TITLE
Value specified in a region column not read

### ISSUE THREAD

**Issue by olejandro** [samwebster/times-excel-reader#60]
Another source of regression is  the value for ``COM_IE` not read (e.g. see demo 3, syssettings, sheet Constants, cell F10)

_Originally posted by @olejandro in https://github.com/samwebster/times-excel-reader/issues/58#issuecomment-1473099241_

**Comment by siddharth-krishna** [comment]
In Demo 3, `COM_IE` is specified in a `~TFM_INS` table. So fixing #57 should also fix this issue.

**Comment by siddharth-krishna** [comment]
Turns out COM_IE is read, but it doesn't appear in either TFM_INS or FI_T in `merged_tables.txt`, so further investigation is needed.

**Comment by olejandro** [comment]
Great! Thanks, @siddharth-krishna . Here the order of the columns is important, i.e. columns to the right should overwrite what is specified in the columns to the left.
How about melting `AllRegions` and region-specific columns into a single `Region`?

**Comment by olejandro** [comment]
Btw, we should probably check whether there is `Value` column and rename it to `AllRegions`. Part of  normalisation?

**Comment by siddharth-krishna** [comment]
How can we do both? Imagine this example also had a Reg2 column with a non empty value. How would we transform it into a table that didn't have a Value column and a single column for region? Or do you mean move values in the Value column to AllRegion and later have a table with a Region and a Value column?

**Comment by olejandro** [comment]
I meant the latter, but let's wait with renaming `Value`, because if the original table already has `Region` and `Value` columns we may generate additional records by renaming it (depending on the processing steps that follow)...

**Comment by siddharth-krishna** [comment]
Okay so to confirm: for now we use a Region column to denote which region and a Value column to denote the attribute value?

Also, does this rule of "values to the right take precedence" apply elsewhere/to other tags or column types?

**Comment by olejandro** [comment]
Yes, using  Region column to denote which region and a Value column to denote the attribute value is correct.
"Values to the right take precedence" rule should apply to any cell that holds an attribute value. This is similar to rows below taking precendence over rows above. So actually melting columns should give the desired effect.

**Comment by siddharth-krishna** [comment]
Okay thanks, I'll implement this. 

Not sure what exactly you mean by "melting" columns?

**Comment by olejandro** [comment]
thanks, @siddharth-krishna !
By melting I mean this: https://pandas.pydata.org/docs/reference/api/pandas.melt.html

**Comment by siddharth-krishna** [comment]
On the call, we worked out some example tables and the desired output of this transform:
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/10712637/229158728-dfdca608-8434-4f02-9523-cafb499a014e.png">
